### ISSUE TITLE
We need you again.

### ISSUE THREAD

**Issue by fireq** [TU6/about#14]
There's something going on again.
I don't if you heard something about the new issues with PokeStops, but I'll shortly explain it.
It's not possible anymore to loot PokeStops using the API, but it isn't a softban. You can still catch Pokemon. Seems like they changed the way servers worked or they changed their softban.
Maybe you can solve it, Team Unknown 6 <3.
-fireq

Edit: Ok, looting PokeStops is still possible. Close the issue, please.

**Comment by huibk89** [comment]
well.. looks like you got a point there.
an unused PTC account still works, a google account still works, but 3 most used PTC accounts all have the problem you describe.
looting a fort always returns out_of_range..
the goodold unban trick doenst seem to work..

anyone found out something about this?

**Comment by keyphact** [comment]
Wrong place, wrong time, wrong words, wrong everything
